### ISSUE TITLE
Failed to emoji generation

### ISSUE THREAD

**Issue by tenk-9** [taniiicom/emorize#44]
bug report.
following `/emorize` command failed to emoji generation.

```
/emorize text:AR name:AR color:cyan
```

executed at 2024/04/16 12:11

**Comment by taniiicom** [comment]
## investigations

`cloud-run > logs`

<img width="1557" alt="Screenshot 2024-04-16 at 15 00 54" src="https://github.com/taniiicom/emorize/assets/89822124/60cee7de-f435-46a3-9737-600a70866020">

- これ原因が, Bot に `MANAGE_EMOJI_AND_STICKER` 権限が存在しないことによるものでした. 
- ~`MANAGE_EMOJI_AND_STICKER` 権限は, Bot 追加時に要求されるはずなので, なぜなかったのか不明~
- Bot 追加を https://emorize.megrio.com から行った場合は, クエリパラメータを介して必要な権限が正しく要求されるのに対して,
- Discord 内の Bot のプロフィールページから, `アプリを追加` で, 他のサーバに登録した場合, 権限が不足していることが分かった
  - Discord Developer コンソールの設定が原因
- とりあえず, エラーメッセージに, 「サーバ権限不足なので追加して欲しい」旨を分岐して表示させる

## solutions

- [provisional] emorize ロールに, `絵文字を管理` 権限を渡す

<img width="1736" alt="Screenshot 2024-04-16 at 14 22 23" src="https://github.com/taniiicom/emorize/assets/89822124/53c18033-b6ff-43a8-b59e-956709256010">

- Discord Developer Portal > Installation > Install Link > Custom URL に変更 ☆^^
```
https://discord.com/oauth2/authorize?client_id=1223599482583777340&permissions=278099134464&scope=bot+applications.commands
```

- to: #45

**Comment by tenk-9** [comment]
ty!

**Comment by taniiicom** [comment]
## snaps
<img width="1710" alt="Screenshot 2024-04-22 at 19 49 25" src="https://github.com/taniiicom/emorize/assets/89822124/e0e8e51c-b600-446b-9ec2-9e5a0316cca3">
